Invitation = ['Ali', 'Maha' , 'Noor' ]
print(Invitation[0] + "I would like to ivite you to dinner ")
print(Invitation[1] + "I would like to ivite you to dinner ")
print(Invitation[2] + "I would like to ivite you to dinner ")
print(Invitation[0] + "can not make it")
Invitation.pop(0)
Invitation.append('khatira')
print(Invitation)
print(Invitation[0] + "I would like to ivite you to dinner ")
print(Invitation[1] + "I would like to ivite you to dinner ")
print(Invitation[2] + "I would like to ivite you to dinner ")
